spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.0.109:1433;database=Terra
    username: sa
    password: issl
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
terra:
  multi-tenancy:
    ISSL:
      url: jdbc:sqlserver://192.168.0.109:1433;database=Terra
      username: sa
      password: issl
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    datasource2:
      url: jdbc:mysql://192.168.0.109:3306/tenant_2
      username: user
      password: password
      driver-class-name: com.mysql.jdbc.Driver
    datasource3:
      url: jdbc:mysql://192.168.0.109:3306/tenant_3
      username: user
      password: password
      driver-class-name: com.mysql.jdbc.Driver
endpoints:
  jmx:
    domain: terra-storage
umaas:
  log: target
logging:
  file: ${umaas.log}/terra-storage.log